[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "coreutils"]

[phases.build]
cmds = [
  "mkdir -p storage/app/firebase",
  "echo $FIREBASE_CREDENTIALS_BASE64 | base64 -d > storage/app/firebase/firebase_credentials.json",
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php -S 0.0.0.0:8080 -t public"
