[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs", "coreutils"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php -S 0.0.0.0:8080 -t public"
